"""
Bass Pro Shops - BA Agent with Claude Tool Use API
Task 5.3: Building BA Agents with Claude's Tool Use API

This is an AGENT not a pipeline:
- You give Claude a goal
- Claude decides which tools to call and when
- Claude iterates until the goal is complete
- Human approval required before email sends

Usage:
  python ba_agent.py

Environment variables:
  ANTHROPIC_API_KEY
  EMAIL_SENDER
  EMAIL_PASSWORD
  EMAIL_RECIPIENTS
"""

import os
import json
import glob
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

import pandas as pd
import anthropic

EXCEL_FILE        = "BassProShops_Weekly_KPI_Report.xlsx"
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "YOUR_API_KEY_HERE")
MODEL             = "claude-sonnet-4-20250514"
EMAIL_SENDER      = os.environ.get("EMAIL_SENDER", "")
EMAIL_PASSWORD    = os.environ.get("EMAIL_PASSWORD", "")
EMAIL_RECIPIENTS  = os.environ.get("EMAIL_RECIPIENTS", "")


# TOOL FUNCTIONS

def get_kpi_data():
    df = pd.read_excel(EXCEL_FILE, sheet_name="Data for Python", header=None)
    header_row = None
    for i, row in df.iterrows():
        if any(str(v).strip().lower() == 'kpi_key' for v in row.values):
            header_row = i
            break
    df.columns = df.iloc[header_row]
    df = df[header_row + 1:].reset_index(drop=True)
    df.columns = ["kpi_key", "this_week", "last_week", "target", "unit"]
    df = df[df["kpi_key"].notna() & (df["kpi_key"].astype(str).str.strip() != "nan")]

    lines = ["KPI                        | This Week | Last Week | Target   | vs Target | WoW"]
    lines.append("-" * 85)
    for _, row in df.iterrows():
        key = str(row["kpi_key"]).strip()
        try:
            tw  = float(row["this_week"])
            lw  = float(row["last_week"])
            tg  = float(row["target"])
            pvt = ((tw - tg) / tg * 100) if tg else 0
            pvl = ((tw - lw) / lw * 100) if lw else 0
            lines.append(f"{key:<30} | {tw:>9.1f} | {lw:>9.1f} | {tg:>8.1f} | {pvt:>+8.1f}% | {pvl:>+.1f}%")
        except (ValueError, TypeError):
            pass
    return "\n".join(lines)


def search_docs(query):
    issues_df = pd.read_excel(EXCEL_FILE, sheet_name="Issues & Actions", header=None)
    issues_df.columns = issues_df.iloc[1]
    issues_df = issues_df[2:].reset_index(drop=True)

    results = []
    query_lower = query.lower()
    for _, row in issues_df.iterrows():
        area   = str(row.get("Area", "")).strip()
        issue  = str(row.get("Issue / Risk", "")).strip()
        owner  = str(row.get("Owner", "")).strip()
        due    = str(row.get("Due Date", "")).strip()
        status = str(row.get("Status", "")).strip()
        combined = f"{area} {issue}".lower()
        if any(word in combined for word in query_lower.split()):
            results.append(f"[{area}] {issue}\n  Owner: {owner} | Due: {due} | Status: {status}")

    if results:
        return f"Found {len(results)} relevant issue(s) for '{query}':\n\n" + "\n\n".join(results)
    return f"No open issues found matching '{query}'."


def format_report(narrative, audience="VP of Sales"):
    week_ending = datetime.today().strftime("%B %d, %Y")
    paragraphs = "".join(f"<p>{p}</p>" for p in narrative.split("\n") if p.strip())
    html = f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif; max-width:700px; margin:auto; color:#222;">
    <div style="background:#1a6c3c; color:white; padding:16px 20px; border-radius:8px 8px 0 0;">
        <h1 style="margin:0; font-size:20px;">Bass Pro Shops - Weekly Sales Briefing</h1>
        <p style="margin:4px 0 0; font-size:13px; opacity:.85;">For: {audience} | Week Ending: {week_ending}</p>
    </div>
    <div style="border:1px solid #ccc; border-top:none; padding:20px; border-radius:0 0 8px 8px;">
        {paragraphs}
        <p style="color:#888; font-size:11px; margin-top:30px;">Generated by BA Agent - Powered by Claude Tool Use API</p>
    </div>
</body>
</html>"""
    out_path = f"agent_report_{datetime.today().strftime('%Y%m%d_%H%M')}.html"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    return f"Report formatted and saved as {out_path}. Ready to send."


def send_email(subject, report_path):
    if not EMAIL_SENDER or not EMAIL_PASSWORD or not EMAIL_RECIPIENTS:
        return "Email credentials not configured. Report saved locally only."
    with open(report_path, "r", encoding="utf-8") as f:
        html_body = f.read()
    recipients = [r.strip() for r in EMAIL_RECIPIENTS.split(",") if r.strip()]
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = EMAIL_SENDER
    msg["To"]      = ", ".join(recipients)
    msg.attach(MIMEText(html_body, "html", "utf-8"))
    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        server.sendmail(EMAIL_SENDER, recipients, msg.as_string())
    return f"Email sent successfully to: {', '.join(recipients)}"


# TOOL DEFINITIONS - what Claude sees

TOOLS = [
    {
        "name": "get_kpi_data",
        "description": "Pull this week's KPI data from the Bass Pro Shops Excel export. Always call this first.",
        "input_schema": {"type": "object", "properties": {}, "required": []}
    },
    {
        "name": "search_docs",
        "description": "Search internal issue logs for context on a metric or anomaly.",
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Topic or metric to search for"}
            },
            "required": ["query"]
        }
    },
    {
        "name": "format_report",
        "description": "Format the completed narrative into a professional HTML report. Only call when analysis is done.",
        "input_schema": {
            "type": "object",
            "properties": {
                "narrative": {"type": "string", "description": "The complete written briefing"},
                "audience":  {"type": "string", "description": "Who the report is for", "default": "VP of Sales"}
            },
            "required": ["narrative"]
        }
    },
    {
        "name": "send_email",
        "description": "Send the formatted report by email. Call this as the final step.",
        "input_schema": {
            "type": "object",
            "properties": {
                "subject":     {"type": "string", "description": "Email subject line"},
                "report_path": {"type": "string", "description": "Path to the HTML report file"}
            },
            "required": ["subject", "report_path"]
        }
    }
]


# TOOL EXECUTOR

def execute_tool(tool_name, tool_input):
    print(f"\n  >> Executing: {tool_name}({json.dumps(tool_input) if tool_input else ''})")
    if tool_name == "get_kpi_data":
        result = get_kpi_data()
    elif tool_name == "search_docs":
        result = search_docs(tool_input["query"])
    elif tool_name == "format_report":
        result = format_report(tool_input["narrative"], tool_input.get("audience", "VP of Sales"))
    elif tool_name == "send_email":
        result = send_email(tool_input["subject"], tool_input["report_path"])
    else:
        result = f"Unknown tool: {tool_name}"
    print(f"  << Result: {result[:120]}...")
    return result


# HUMAN APPROVAL CHECKPOINT

def request_human_approval(report_path):
    print("\n" + "="*60)
    print("  HUMAN APPROVAL REQUIRED")
    print("="*60)
    print(f"  Report saved: {report_path}")
    print("  Open the HTML file to review it.")
    print("="*60)
    print("\n  Options:")
    print("  - Type  yes  to approve and send")
    print("  - Type  no   to cancel")
    print("  - Type any feedback and Claude will revise and auto-send")
    response = input("\n  Your decision: ").strip()

    if response.lower() in ["yes", "y"]:
        print("\n  Approved! Sending email...")
        return "approved", None

    if response.lower() in ["no", "n"]:
        print("\n  Cancelled. Report saved locally only.")
        return "declined", None

    # Feedback given
    print(f"\n  Got it. Claude will revise based on your feedback and auto-send...")
    return "feedback", response


# AGENT LOOP

def run_agent():
    print("\n" + "="*60)
    print("  Bass Pro Shops BA Agent - Starting")
    print("="*60 + "\n")

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    goal = """Analyse this week's Bass Pro Shops sales data and write a briefing for the VP of Sales.

Your briefing must:
- Highlight the 2 strongest performing metrics with specific numbers
- Identify the most concerning anomaly and find its root cause using search_docs
- End with 1 clear recommended action for the VP

Work through these steps in order:
1. Call get_kpi_data()
2. Analyse the data, identify anomalies
3. Call search_docs() on anything unusual
4. Write the full narrative
5. Call format_report() with the completed narrative
6. Call send_email() as the final step"""

    messages = [{"role": "user", "content": goal}]
    report_path = None
    approved = False

    while True:
        print("\nClaude is thinking...")
        response = client.messages.create(
            model=MODEL,
            max_tokens=4096,
            tools=TOOLS,
            messages=messages,
        )

        messages.append({"role": "assistant", "content": response.content})

        if response.stop_reason == "end_turn":
            for block in response.content:
                if hasattr(block, "text"):
                    print(f"\n-- AGENT FINAL OUTPUT --\n{block.text}")
            break

        if response.stop_reason == "tool_use":
            tool_results = []

            for block in response.content:
                if hasattr(block, "text") and block.text:
                    print(f"\nClaude: {block.text}")

                if block.type == "tool_use":
                    print(f"\nClaude wants to call: {block.name}")

                    # Intercept send_email for human approval
                    if block.name == "send_email" and not approved:
                        # Find the latest report file
                        files = glob.glob("agent_report_*.html")
                        if files:
                            report_path = max(files)

                        decision, feedback = request_human_approval(report_path)

                        if decision == "declined":
                            tool_results.append({
                                "type": "tool_result",
                                "tool_use_id": block.id,
                                "content": "Human declined to send. Report saved locally only."
                            })
                            continue

                        elif decision == "feedback":
                            # Ask Claude to revise then auto-send
                            approved = True
                            tool_results.append({
                                "type": "tool_result",
                                "tool_use_id": block.id,
                                "content": f"Human requested revisions before sending: {feedback}. Please revise the narrative, call format_report() again with the updated version, then call send_email() to send it."
                            })
                            continue

                        else:
                            # Approved - let it send
                            approved = True

                    result = execute_tool(block.name, block.input)

                    # Track report path
                    if block.name == "format_report":
                        files = glob.glob("agent_report_*.html")
                        if files:
                            report_path = max(files)

                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": result
                    })

            messages.append({"role": "user", "content": tool_results})

    print("\nAgent complete.\n")


if __name__ == "__main__":
    run_agent()
